export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';
export const LOAD_PRODUCT = 'LOAD_PRODUCT';
export const CHECKOUT_BASKET = 'CHECKOUT_BASKET';
export const ADD_TO_BASKET = 'ADD_TO_BASKET';
export const REMOVE_FROM_BASKET = 'REMOVE_FROM_BASKET';
export const SHOW_ERROR = 'SHOW_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
